language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - bash -c 'if [ $(phpenv version-name) = "5.6" ]; then vendor/bin/test-reporter; fi;'
